---
-
  name: "Download woocommerce from wp cli command"
  command: "wp plugin install wordpress importer --path='{{webroot}}/wordpress'"
  
-
  name: "Activate woocommerce with wp cli command"
  command: "wp plugin activate wordpress importer --path='{{webroot}}/wordpress'"
