---
- name: download wpcli
  get_url:
    dest: "/home/azureadmin"
    group: "www-data"
    owner: "www-data"
    url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
  become: yes

- name: install wp-cli
  command: "chmod +x /home/azureadmin/wp-cli.phar"
  become: yes

- name: move wp-cli
  command: "mv /home/azureadmin/wp-cli.phar /usr/local/bin/wp"
  become: yes

