- hosts: 127.0.0.1
  connection: local
  roles:
    - sshkeyconfig
    - export
    - copyxmlfile
    
- hosts: webservers
  roles:
     - wordpressimporter
     - movexmlfile
     - importwordpress
     - replication
