- hosts: 127.0.0.1
  connection: local
  roles:
    - sshkeyconfig
    - export
    - copyfile
    
- hosts: webservers
  roles:
     - wordpressimport
     - movefile
     - replication
     - importwordpress
  
