- hosts: 127.0.0.1
  connection: local
  roles:
   # - sshkeyconfig
   # - exportfile
   # - databaseexport
   # - copyexportfiles
    - exportplugins
    
    
- hosts: webservers
  roles:
    #- wordpress
    #- woocommerce
    - importplugins
   # - databaseimport
   # - wordpressimporterplugin
   # - moveexportfiles
    #- import_wordpress
    - replication
