- hosts: 127.0.0.1
  connection: local
  roles:
    - sshkeyconfig
    - export
    - databaseexport
    - copyxmlfile
    
    
- hosts: webservers
  roles:
     #- databaseimport
     - wordpressimporter
     - movexmlfile
     - importwordpress
     - replication
