- hosts: 127.0.0.1
  connection: local
  roles:
    - sshkeyconfig
    - exportfile
    - databaseexport
    - copyexportfiles
    
    
- hosts: webservers
  roles:
    - databaseimport
    - wordpressimporter
    - moveexportfiles
    - importwordpress
     #- wordpress
     #- woocommerce
    - replication
