- hosts: 127.0.0.1
  connection: local
  roles:
    - sshkeyconfig
    - wordpress
    - woocommerce
    - export
    - databaseexport
    - copyexportfile
    
    
- hosts: webservers
  roles:
     - databaseimport
     - wordpressimporter
     - moveexportfiles
     - importwordpress
     - replication
