- hosts: 127.0.0.1
  connection: local
  roles:
    - sshkeyconfig
    - exportfile
    - databaseexport
    - copyexportfiles
    - plugins
    - media
    
    
- hosts: webservers
  roles:
    #- wordpress
    #- woocommerce
    - mediaimport
    - importplugins
    - databaseimport
    - wordpressimporterplugin
    - moveexportfiles
    - import_wordpress
    - replication
