---
- name: download wpcli
  get_url:
    dest: "/home/azureadmin"
    group: "www-data"
    owner: "www-data"
    url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
  become: yes

- name: install wp-cli
  command: "chmod +x /home/azureadmin/wp-cli.phar"
  become: yes

- name: move wp-cli
  command: "mv /home/azureadmin/wp-cli.phar /usr/local/bin/wp"
  become: yes
  
- name: export wordpress site
  command: wp export --dir=/tmp/ --post_type=post,page,attachment,revision,nav_menu_item,custom_css,customize_changeset,oembed_cache,user_request,wp_block --path=/azlamp/html/lampwordpress.com
  
