---
- name: download wpcli
  get_url:
    dest: "/home/{{user_name}}"
    group: "{{default_permission}}"
    owner: "{{default_permission}}"
    url: "{{wp_cli_url}}"
  become: yes

- name: install wp-cli
  command: "chmod +x /home/{{user_name}}/wp-cli.phar"
  become: yes

- name: move wp-cli
  command: "mv /home/{{user_name}}/wp-cli.phar /usr/local/bin/wp"
  become: yes
- name: create xml directory
  command: mkdir /tmp/wp-xml
- name: change permissions
  command: chmod 777 /tmp/wp-xml
  become: yes
- name: export xml file
  command: wp export --dir=/tmp/wp-xml --post_type=post,page,attachment,revision,nav_menu_item,custom_css,customize_changeset,oembed_cache,user_request,wp_block --path=/azlamp/html/{{ domain_name}}
- name: move xml file
  move:
    src: /tmp/wp-xml/*
    dest: /tmp/wp-xml/wp-export.xml
  become: yes
  
  
