--- 
- name: create a backup
  mysql_db:
    name: wordpress
    state: dump
    target: /var/www/html/wordpress.sql
  
#- name: copy the database to the development server
 # raw: rsync /var/www/html/wordpress.sql root@192.168.0.69:/home/vagrant/wordpress.sql

#- name: import the database
#  mysql_db:
 # name: wordpress
 # state: import
  #target: /home/vagrant/wordpress.sql
  #login_host: 192.168.0.69
 # login_user: root
 # login_password: '123456'






