---

- name: activate wordpress-importer 
  command: "wp plugin activate wordpress-importer --path={{tar_wordpress_path}}"
  
  
- name: download wpcli
  get_url:
    dest: "/home/{{user_name}}"
    group: "{{default_permission}}"
    owner: "{{default_permission}}"
    url: "{{wp_cli_url}}"
  become: yes

- name: install wp-cli
  command: "chmod +x /home/{{user_name}}/wp-cli.phar"
  become: yes

- name: move wp-cli
  command: "mv /home/{{user_name}}/wp-cli.phar /usr/local/bin/wp"
  become: yes
  
- name: import wordpress site
  command: "wp import {{tar_wordpress_path}}/{{file_format}} --authors=create --path={{tar_wordpress_path}}"
  
