
--- 
- name: Install MySQL 
  apt: 
    name: mysql-server
    state: latest
  become: yes

- name: Install MySQL 
  command: sudo apt-get install mysql-server mysql-common mysql-client
  
  
- 
  get_url: 
    dest: "/home/{{ user_name | quote }}"
    group: "{{ user_name | quote }}"
    mode: 493
    owner: "{{ user_name | quote }}"
    url: "{{sql_dump_url}}"
  name: "Download sql_dump.sh script using get_url"
- 
  args: 
    executable: /bin/bash
  name: "Run a sql_dump.sh script with arguments (using 'cmd' parameter)"
  shell: "/home/{{ user_name | quote }}/{{ sql_dump_script_name | quote }} {{ wp_db_name_tar | quote }}"
