---

- name: remove plugins
  command: rm -r /azlamp/html/lb-yw23wf.eastus.cloudapp.azure.com/wp-content/plugins/
  become: yes


- name: import plugins.zip
  unarchive:
    src: /home/azureadmin/plugins.zip
    dest: /home/azureadmin/
    owner: "{{default_permission}}"
    group: "{{default_permission}}"
    copy: no
  become: yes
  
- name: change permissions
  command: chown www-data:www-data /azlamp/html/lb-yw23wf.eastus.cloudapp.azure.com/wp-content/plugins
  become: yes
 


