- name: move plugins zip file
  command: mv /home/{{user_name}}/plugins.zip  /{{tar_wordpress_path}}/wp-content/plugins
  become: true 

- name: Extract plugins.zip
  unarchive:
    src: /azlamp/html/lb-yw23wf.eastus.cloudapp.azure.com/wp-content/plugins/plugins.zip
    dest: /azlamp/html/lb-yw23wf.eastus.cloudapp.azure.com/wp-content/plugins
    remote_src: yes
