---

- name: remove plugins
  command: rm -r /azlamp/html/lb-yw23wf.eastus.cloudapp.azure.com/wp-content/plugins/

- name: import plugins.zip
  unarchive:
    src: /home/azureadmin/plugins.zip
    dest: /home/azureadmin/
    owner: "{{default_permission}}"
    group: "{{default_permission}}"
    copy: no
  become: yes
 

- name: move plugins zip file
  command: "mv /home/azureadmin/plugins/ /azlamp/html/lb-yw23wf.eastus.cloudapp.azure.com/wp-content/"
  become: yes
