

- name: Extract plugins.zip
  unarchive:
    src: /home/azureadmin/plugins.zip
    dest: /home/azureadmin/
    owner: "{{default_permission}}"
    group: "{{default_permission}}"
    copy: no
  
- name: move plugins zip file
  command: cp /home/{{user_name}}/plugins /azlamp/html/lb-yw23wf.eastus.cloudapp.azure.com/wp-content/
  become: true 
