---
- name: download wpcli
  get_url:
    dest: "/home/{{user_name}}"
    group: "{{default_permission}}"
    owner: "{{default_permission}}"
    url: "{{wp_cli_url}}"
  become: yes

- name: install wp-cli
  command: "chmod +x /home/{{user_name}}/wp-cli.phar"
  become: yes

- name: move wp-cli
  command: "mv /home/{{user_name}}/wp-cli.phar /usr/local/bin/wp"
  become: yes
  
- name: create xml directory
  command: mkdir {{xml_path}}
  
- name: change permissions
  command: chmod 777 {{xml_path}}
  become: yes
  
- name: export xml file
  command: "wp export --dir={{xml_path}} --post_type={{post_type}} --filename_format={{file_format}} --path={{src_wordpress_path}}"

- name: change permissions
  command: chmod 755 {{xml_path}}
  become: yes

  
  
