---
   - name: "upgrade"
     apt:
      upgrade: true
     become: true

   - name: "install sshpass"
     #command: apt-get install sshpass
     apt:
       name: sshpass
       state: latest
     become: yes

   - name: “generate sshkey”
     openssh_keypair:
      path: /home/azureadmin/.ssh/id_rsa
      group: www-data
      owner: www-data
      size: 4096
     become: yes
      
   - name: "copy file to remote host"
     command: sshpass -p iTalent@27 ssh-copy-id -i /home/azureadmin/.ssh/id_rsa.pub -o StrictHostKeyChecking=no azureadmin@137.116.127.83
